namespace AIHub.Services;

public sealed record FinancialExpertRole(string RussianTitle, string EnglishTitle, string RussianTask, string EnglishTask)
{
    public string Title(string language) => language == "en" ? EnglishTitle : RussianTitle;
    public string Task(string language) => language == "en" ? EnglishTask : RussianTask;
}

/// <summary>Separate mandates: specialists interpret evidence, report editors synthesize it.</summary>
public static class FinancialAnalysisRoles
{
    public static FinancialExpertRole For(string id) => id switch
    {
        "overview" => new("Эксперт по структуре личного бюджета", "Personal budget structure expert",
            "Объясните, как обязательная нагрузка, выбираемые расходы и состав дохода сочетаются между собой. Найдите главный компромисс или опору бюджета. Положительный остаток сам по себе не доказывает наличие накоплений или финансовую защищённость.",
            "Explain how required commitments, chosen spending and income composition interact. Identify the main trade-off or support of this budget. A positive balance alone proves neither savings nor financial security."),
        "required" => new("Аналитик обязательств и гибкости расходов", "Commitments and spending flexibility analyst",
            "Изучите, как жильё, питание и коммунальные статьи ограничивают пространство выбора относительно дохода и других расходов. Категория обязательных расходов не доказывает неизменность каждой суммы; не объявляйте её чрезмерной без основания.",
            "Examine how housing, food and utilities constrain choice relative to income and other expenses. Membership in the required category does not make each amount immutable; do not call it excessive without evidence."),
        "everyday" => new("Эксперт по повседневной финансовой нагрузке", "Everyday financial burden expert",
            "Сопоставьте питание, связь, интернет и гигиену с расходами на удобство и досуг. Объясните возможное сочетание базовых потребностей и выбранных услуг. Не выводите количество покупок или расточительность из регулярной суммы.",
            "Relate food, phone, internet and hygiene to convenience and leisure spending. Explain the possible mix of basic needs and chosen services. Do not infer purchase frequency or wastefulness from a recurring amount."),
        "subscriptions" => new("Аудитор регулярных подписок", "Recurring subscriptions auditor",
            "Рассмотрите совокупность подписок, их место рядом с другими выбираемыми статьями и доходом. Если есть основания, предложите проверить использование конкретных сервисов. Анкета не сообщает полезность или дублирование: не объявляйте подписки ненужными автоматически.",
            "Assess the combined subscriptions in relation to other chosen expenses and income. Where justified, suggest checking use of named services. The questionnaire does not establish usefulness or duplication; do not automatically declare subscriptions unnecessary."),
        "transport" => new("Эксперт по транспортной нагрузке", "Transport spending expert",
            "Сопоставьте общественный транспорт, такси и автомобильные статьи; исследуйте сочетание альтернатив и нагрузку на бюджет. Не предполагайте маршруты, владение автомобилем, расстояния или возможность заменить поездки без сведений.",
            "Compare public transport, taxis and car-related items; examine the mix of alternatives and its budget burden. Do not assume routes, car ownership, distances or substitutability without evidence."),
        "health" => new("Аналитик финансовых расходов на здоровье", "Health expenditure analyst",
            "Рассмотрите лекарства, линзы, контрацепцию и спорт в связи с общей гибкостью бюджета. Различайте потенциально защищаемые потребности и варианты выбора, если данных достаточно. Не советуйте отменять лечение и не делайте медицинских выводов.",
            "Relate medicine, lenses, contraception and sport to overall budget flexibility. Distinguish potentially protected needs from choices where evidence permits. Do not recommend stopping treatment or draw medical conclusions."),
        "pleasures" => new("Аналитик необязательных регулярных расходов", "Discretionary recurring spending analyst",
            "Изучите конкретные статьи удовольствий и хобби, их концентрацию и связь с личной нагрузкой и доходом. Называйте статьи, а не только категорию «удовольствия». Если одна статья заметно влияет на свободу бюджета, объясните возможный компромисс и условный вариант её пересмотра. Не морализируйте и не приписывайте зависимости, импульсивность или мотивы.",
            "Examine individual pleasures and hobbies, their concentration and relation to personal burden and income. Name the items, not just the discretionary category. If an item materially affects budget flexibility, explain the potential trade-off and a conditional option to review it. Do not moralize or attribute addiction, impulsivity or motives."),
        "personal" => new("Эксперт по расходам на личный уход", "Personal care spending expert",
            "Сопоставьте гигиену и другие статьи ухода с выбираемыми расходами и общими возможностями бюджета. Различайте структуру и оценку ценности; не делайте выводов о внешности, гендере или необходимости конкретной услуги.",
            "Relate hygiene and other personal care items to chosen expenses and budget capacity. Distinguish spending structure from value judgments; infer neither appearance, gender nor the necessity of a service."),
        "pets" => new("Аналитик постоянной нагрузки по уходу за животными", "Recurring pet care burden analyst",
            "Рассмотрите сочетание питания, наполнителя и ухода как отдельного обязательства относительно остальных расходов. Сведения не устанавливают число животных или резерв на ветеринара. Не предлагайте ухудшать базовый уход ради экономии.",
            "Assess food, litter and care as a distinct commitment relative to other expenses. The data establishes neither animal count nor veterinary reserves. Do not suggest reducing basic care to save money."),
        "education" => new("Эксперт по финансированию образования", "Education funding expert",
            "Сопоставьте обучение, курсы и репетитора со стабильным доходом и выбираемыми расходами. Обсудите, как регулярная учебная нагрузка сочетается с бюджетом. Не обещайте рост дохода и не называйте образование окупаемым без данных об использовании и целях.",
            "Relate tuition, courses and tutoring to stable income and chosen spending. Discuss compatibility of recurring education commitments with the budget. Do not promise earnings growth or a return on education without evidence of use and goals."),
        "relatives" => new("Эксперт по регулярной поддержке близких", "Recurring family support expert",
            "Отделите собственные переводы близким от полученной внешней оплаты. Оцените, как поддержка других соотносится с личными обязательствами и источниками дохода. Не предполагайте состав семьи, добровольность или возможность прекратить поддержку.",
            "Separate the user's transfers to relatives from outside payment received. Assess support for others relative to personal commitments and income sources. Do not assume family composition, voluntariness or the ability to stop support."),
        "external" => new("Эксперт по внешнему финансированию расходов", "External expense funding expert",
            "Изучите, какие потребности полностью или частично оплачиваются извне и как это влияет на видимую самостоятельную нагрузку. Статус оплаты не показывает размер, устойчивость или условия помощи. Не угадывайте чужие суммы и не считайте помощь доходом.",
            "Examine which needs are fully or partly paid from outside and how this affects observed personal burden. Payment status establishes neither amount, reliability nor conditions of support. Do not estimate other people's money or count support as income."),
        "largest" => new("Эксперт по концентрации расходов", "Expense concentration expert",
            "Определите не просто крупнейшую строку, а последствия концентрации: какие статьи сильнее определяют гибкость бюджета и возможный эффект пересмотра. Сопоставьте управляемость крупных и мелких расходов, не объявляя большую долю проблемой автоматически.",
            "Identify the implications of concentration, not merely the largest row: which items most determine flexibility and potential review effects. Compare controllability of large and small items without automatically treating a large share as a problem."),
        "missing" => new("Аудитор полноты и достоверности финансовых вводных", "Financial input completeness auditor",
            "Определите, какие выводы поддержаны, какие ограничены пропусками и какие вопросы действительно изменили бы оценку. Известный ноль отличается от пропуска. Даже полная анкета регулярных расходов ничего не доказывает о накоплениях, долгах и разовых платежах вне анкеты.",
            "Identify supported conclusions, those limited by missing entries, and questions that could materially change the assessment. A known zero differs from a missing entry. Even a complete recurring-expense questionnaire proves nothing about savings, debts or one-off payments outside it."),
        "economy" => new("Эксперт по адресному пересмотру расходов", "Targeted spending review expert",
            "Ищите подтверждённые данные, которые делают пересмотр конкретной статьи разумным. Значимая управляемая статья может дать эффект даже без сведений об альтернативах и целях: предложите рассмотреть её сокращение при готовности пользователя, а не заменяйте это общим советом. Это условная возможность, не доказательство лишнего расхода. Для каждого предложения назовите статью, основание, качественный эффект и условие. Не придумывайте цены и суммы экономии. Если явной точки улучшения нет, сообщите об этом.",
            "Seek evidence that makes reviewing a specific item reasonable. A material controllable item may offer an effect even without known alternatives or goals: suggest considering its reduction if the user is willing, not generic optimization. This is a conditional opportunity, not proof of waste. For each suggestion name the item, evidence, qualitative effect and condition. Invent neither prices nor savings amounts. State when no clear improvement is apparent."),
        "resilience" => new("Эксперт по устойчивости финансирования бюджета", "Budget funding resilience expert",
            "Различите зависимость от дополнительного дохода и зависимость от оплаты потребностей другими. Рассмотрите, какие обязательства останутся при изменении этих опор, без выдуманного сценария или размера помощи. Положительный остаток не равен резерву; стабильный доход не гарантирован навсегда.",
            "Distinguish dependence on additional income from reliance on others paying for needs. Examine which commitments remain if these supports change without inventing scenarios or support amounts. A positive balance is not a reserve; stable income is not guaranteed forever."),
        "alignment" => new("Эксперт по совместимости доходов и обязательств", "Income and commitment alignment expert",
            "Проверьте, что поддерживает регулярные личные расходы: стабильный доход, дополнительный доход либо известная помощь. Объясните значение состава финансирования и свободы выбора. Не ограничивайтесь словами о знаке остатка; при пропусках сохраняйте условность вывода.",
            "Examine what supports recurring personal expenses: stable income, additional income or recorded support. Explain implications of funding composition and room for choice. Go beyond the balance sign and keep conclusions conditional where data is missing."),
        "simple" => new("Финансовый консультант по понятному объяснению", "Plain-language financial adviser",
            "Передайте главную связь и её смысл для пользователя понятным языком, с опорой на расчёт и заключения аналитиков. Возраст меняет только язык объяснения, не выводы и не нормы расходов. Не пересказывайте таблицу и не давайте шаблонный список советов.",
            "Explain the main relationship and its meaning clearly, using the calculation and specialist conclusions. Age changes presentation only, not conclusions or spending norms. Do not recite the table or provide a generic advice list."),
        "practical" => new("Консультант по персональным финансовым решениям", "Personal financial decision adviser",
            "Выберите обоснованные приоритеты из заключений, проверьте их по данным и предложите конкретные необязательные действия с условиями. Возраст влияет только на понятность подачи. Когда действие не обосновано, лучше обозначить необходимое уточнение или отсутствие явной точки улучшения.",
            "Select evidence-based priorities from the conclusions, verify them against data and suggest specific optional actions with conditions. Age affects clarity only. When action is unsupported, identify a necessary clarification or the lack of a clear improvement instead."),
        "professional" => new("Профессиональный аналитик личных финансов", "Professional personal finance analyst",
            "Синтезируйте механизм бюджета: концентрацию, гибкость, структуру финансирования и границы наблюдений. Отделите подтверждённые факты от интерпретаций, проверьте заключения аналитиков. Сохраните профессиональную глубину независимо от возраста; объясняйте термины без упрощения анализа.",
            "Synthesize the budget mechanism: concentration, flexibility, funding structure and observation limits. Separate confirmed facts from interpretations and verify specialist conclusions. Retain professional depth regardless of age; explain terms without simplifying the analysis."),
        "final" => new("Старший финансовый эксперт", "Senior financial expert",
            "Получите цельную картину из расчёта и полных заключений всех аналитиков. Устраните дубли, проверьте каждый тезис по исходным статьям, отвергните неподтверждённые. Проверяйте, существует ли названный расход, какой у него статус и действительно ли он существенен. Не заменяйте сверку фразой «все заключения согласованы»: назовите существенные отклонённые или исправленные тезисы, если они есть. Неразрешённые противоречия обозначьте явно. Отдельно составьте поведенческий финансовый портрет: только наблюдаемая модель распределения собственных расходов и финансирования, не личность или диагноз. Привяжите каждый персональный совет к конкретной статье и связи в этом портрете. Не подменяйте адресный вывод словами «оптимизировать необязательные расходы». Не предполагайте проблемы заранее: без обоснованного эффекта не рекомендуйте сокращать статьи просто ради сокращения. При отсутствии существенной проблемы или очевидной точки улучшения так и напишите; раздел рекомендаций может сообщать, что изменения не обоснованы.",
            "Form a coherent picture from the calculation and full conclusions of all analysts. Remove duplicates, check each claim against original items and reject unsupported claims. Check whether a named expense exists, its status and whether it is actually material. Do not replace verification with 'all conclusions agree': name material rejected or corrected claims where present. State unresolved contradictions explicitly. Include a separate behavioral financial portrait: only the observed distribution of personal spending and funding, never personality or diagnosis. Tie each personalized recommendation to a specific item and relationship in this portrait. Do not replace targeted conclusions with 'optimize discretionary spending'. Do not presuppose problems: without an evidence-based effect do not recommend cuts for their own sake. State when no material problem or clear improvement is found; the recommendations section may say that changes are not justified."),
        _ => throw new ArgumentOutOfRangeException(nameof(id), id, "Unknown financial expert role.")
    };
}
