using System.Text.Json.Nodes;
using System.IO;

namespace AIHub.Services;

/// <summary>Model-facing view. Full revisions and read receipts remain in the runtime diagnostics.</summary>
public static class LiteraryParagraphPacket
{
    public static object Build(ParagraphRequest request, ParagraphEvidence evidence, LiteraryParagraphCatalog catalog)
    {
        var references = evidence.Materials.Select((m, i) => (m.Id, Ref: "m" + (i + 1)))
            .ToDictionary(x => x.Id, x => x.Ref);
        var covered = request.Selection.Where(x => x.Value.Selected && catalog.Nodes.ContainsKey(x.Key))
            .SelectMany(x => catalog.Nodes[x.Key].All()).Select(x => x.Id).ToHashSet();
        return new
        {
            stage = request.Role.ToString(), task = request.Task,
            working_draft = new { request.Editor.Text, request.Editor.Unsaved, number = request.Editor.Active.Number },
            currentRouteId = request.RouteId,
            current_route = string.IsNullOrEmpty(request.RouteId) ? null : catalog.Routes.GetValueOrDefault(request.RouteId)
                ?? throw new IOException("Selected current route is no longer available. Choose an existing stage."),
            history = request.Role == LiteraryChatProfile.Writer ? Array.Empty<ParagraphTurn>() : request.History,
            materials = evidence.Materials.Select(m => new
            {
                id = references[m.Id], kind = m.Kind,
                source = m.Id[..m.Id.LastIndexOf('@')], data = Content(m)
            }),
            receipts = evidence.Receipts.Select(r => new
            {
                id = r.Id, label = r.Label, status = r.Status,
                materials = r.Materials.Select(id => references[id])
            }),
            scopeComments = request.Selection.Where(x => x.Value.Comment.Length > 0 &&
                request.Selection.Any(s => s.Value.Selected &&
                    (s.Key == x.Key || IsAncestor(catalog, s.Key, x.Key) || IsAncestor(catalog, x.Key, s.Key))))
                .Select(x => new { id = x.Key, comment = x.Value.Comment }),
            available = request.Role == LiteraryChatProfile.Advisor
                ? catalog.Nodes.Values.Where(n => !covered.Contains(n.Id)).Select(n => new { id = n.Id, label = n.Label }).ToArray()
                : null
        };
    }

    private static bool IsAncestor(LiteraryParagraphCatalog catalog, string parent, string child)
        => catalog.Nodes.TryGetValue(parent, out var node) && node.All().Any(n => n.Id == child);

    private static JsonNode? Content(ParagraphMaterial material)
    {
        var data = JsonNode.Parse(ParagraphJson.Encode(material.Data));
        // Only metadata generated by our reader is omitted. User text, labels and memory facts stay verbatim.
        if (material.Kind is "confirmed_creation_intent" or "future_route" or "author_anchor" && data is JsonObject value)
        {
            value.Remove("sourceRevision");
            value.Remove("source");
        }
        return data;
    }
}
